### ISSUE TITLE
Mobile Editor - Top Left (2) Icons Not Functional

### ISSUE THREAD

**Issue by slmessier** [slmessier/ADW-GAMS-Field-Tool#5]
The 2 icons shown below are not currently linked to a function. Users tap on the icons and the system has no apparent response.

![image](https://cloud.githubusercontent.com/assets/4098544/6731435/5a94d476-ce1b-11e4-962e-43b8c14599d6.png)

**Comment by johnshiu** [comment]
These have been removed for now.
